/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingIdRouteImport } from './routes/tracking.$id'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIdRoute = TrackingIdRouteImport.update({
  id: '/tracking/$id',
  path: '/tracking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RestaurantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/tracking/$id': typeof TrackingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/tracking/$id': typeof TrackingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/tracking/$id': typeof TrackingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/offers'
    | '/orders'
    | '/profile'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/restaurants/$id'
    | '/tracking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/offers'
    | '/orders'
    | '/profile'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/restaurants/$id'
    | '/tracking/$id'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/offers'
    | '/orders'
    | '/profile'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/restaurants/$id'
    | '/tracking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TrackingIdRoute: typeof TrackingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$id': {
      id: '/tracking/$id'
      path: '/tracking/$id'
      fullPath: '/tracking/$id'
      preLoaderRoute: typeof TrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof RestaurantsRoute
    }
  }
}

interface RestaurantsRouteChildren {
  RestaurantsIdRoute: typeof RestaurantsIdRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsIdRoute: RestaurantsIdRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  RestaurantsRoute: RestaurantsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TrackingIdRoute: TrackingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
